library(knitr)
library(markdown)
library(tseries)
library(zoo)
library(RColorBrewer)
library(xtable)
setwd("P:/IMD/Karl/R projects/private investment performance/pmehtml")
load("../pmedata.rdata")
source("../../basic financial.r")
r2kreturn=diff(log(bench.lst[[2]]))
r2kgrowth=exp(cumsum(r2kreturn))
odcereturn=diff(log(bench.lst[[3]]))
odcegrowth=exp(cumsum(odcereturn))
perflength=6+(4*length(bench.lst))
pmeind=grep('PME',colnames(pme.df))
irrind=grep('IRR',colnames(pme.df))
iterator=1:length(pme.df$name)
#iterator=c(1,8,81,128)
for (i in iterator) {
filename=paste0(pme.df$name[i],".rmd")
filecon=file(filename)
text=paste0("# ",rownames(pme.df)[i]," (",pme.df$name[i],")    ")
text=c(text,paste0('SS LPA Services performance calculated through ', as.character(valdate),"    "))
text=c(text,paste0('Cash flow downloaded through ',as.character(lastcfdate),"    "))
text=c(text,paste0('Unfunded amounts as of ',as.character(unfunded.date),"   "))
text=c(text,"   ")
text=c(text,"### Investment Information    ")
cf.i=y.cf[[i]]
cont.i=-sum(cf.i[cf.i<0])
dist.i=sum(cf.i[cf.i>0])
dpi.i=dist.i/cont.i
dpi.i=round(dpi.i*100,2)
dist.i=round(dist.i/1000000)
cont.i=round(cont.i/1000000)
v.i=y.v[[i]]
hv.i=y.hv[[i]]
nopme=all(is.na(pme.df[i,pmeind]))
noirr=all(is.na(pme.df[i,irrind]))
hasperformancedata=(!noirr)&(!nopme)
realized.i=round(100*(1-pme.df$Unreal[i]),2)
text=c(text,"```{r echo=FALSE, fig.width=7, fig.height=4, results='asis'}   ")
text=c(text,"library(zoo)   ")
text=c(text,"library(xtable)   ")
text=c(text,"setwd('P:/IMD/Karl/R projects/private investment performance/pmehtml')   ")
text=c(text,"load('../pmedata.rdata')   ")
text=c(text,paste0("i=",i,"   "))
text=c(text,"perflength=6+(4*length(bench.lst))   ")
text=c(text,"mt=as.character(cats$catlong[which(cats$catshort==pme.df$cat[i])])   ")
text=c(text,"if (0==length(mt)) {mt=' '}    ")
text=c(text,"mt=c(mt,pme.df$vint[i])   ")
text=c(text,"mt=c(mt,pme.df$commit[i])   ")
text=c(text,"mt=c(mt,pme.df$unf[i])   ")
text=c(text,paste0("mt=c(mt,",cont.i,")   "))
text=c(text,paste0("mt=c(mt,",dist.i,")   "))
text=c(text,paste0("mt=c(mt,",dpi.i,")   "))
text=c(text,"mt=matrix(mt,ncol=1)   ")
text=c(text,"rownames(mt)=c('Category   ','Vintage   ','Commitment   ','Unfunded   ','Contributions   '
       ,'Distributions   ','Distributions as % of invested   ')   ")
text=c(text,"colnames(mt)='  '   ")
text=c(text,"xt=matrix(pme.df[i,1:perflength],ncol=2,byrow=TRUE)   ")
text=c(text,"colnames(xt)=c(as.character(valdate),as.character(pme.df$Date.2[i]))   ")
text=c(text,"if(is.na(pme.df$Date.2[i])) {xt=matrix(xt[,1],ncol=1); colnames(xt)=as.character(valdate) }   ")
text=c(text,"rownames(xt)=colnames(pme.df)[-1+(2*(1:(perflength/2)))]   ")
text=c(text,"print(xtable(mt),type='html')   ")
text=c(text,"```   ")
text=c(text,"    ")
text=c(text,"### Performance Summary   ")
text=c(text,"```{r echo=FALSE, results='asis'}   ")
text=c(text,"xt2=as.matrix(xt[-1:(-2*length(benchnames)),])   ")
text=c(text,"colnames(xt2)=colnames(xt)   ")
text=c(text,"print(xtable(xt2),type='html')   ")
text=c(text,"```   ")
text=c(text,"   ")
text=c(text,"   ")
text=c(text,"   ")
text=c(text,"   ")
text=c(text,"## Market context and relative performance")
text=c(text,"```{r echo=FALSE, fig.width=10.5, fig.height=4}   ")
text=c(text,"cf.i=y.cf[[i]]/1000000   ")
text=c(text,"cf.i=cf.i[cf.i!=0]   ")
text=c(text,"cf.i=c(cf.i,zoo(0,lastcfdate+1))    ")
text=c(text,"v.i=y.v[[i]]/1000000   ")
text=c(text,"hv.i=y.hv[[i]]/1000000   ")
text=c(text,"v.i=merge(v.i,hv.i)   ")
text=c(text,"noval=FALSE")
text=c(text,"if(all(is.na(v.i))) {noval=TRUE;minval=0;maxval=0}   ")
text=c(text,"if(!noval) {    ")
text=c(text,"if(length(hv.i)==0) {maxval=minval=v.i} else {")
text=c(text,"v.i$c=v.i$v.i   ")
text=c(text,"vcna=which(is.na(v.i$c))   ")
text=c(text,"v.i$c[vcna]=v.i$hv.i[vcna]   ")
text=c(text,"maxval=max(v.i$c)    ")
text=c(text,"minval=min(v.i$c)    ")
text=c(text,"v.i=v.i$c } }   ")
text=c(text,"cumcfi=cumsum(cf.i)    ")
text=c(text,"ylim=vector()   ")
text=c(text,"ylim[1]=(min(min(-cumcfi),minval))   ")
text=c(text,"ylim[2]=max(max(-cumcfi),maxval)   ")
text=c(text,"if(noval) dateline=index(cf.i)   ")
text=c(text,"if(!noval) dateline=index(merge(cf.i,v.i))   ")
text=c(text,"xlim=c(dateline[1],lastcfdate)    ")
text=c(text,"layout(matrix(c(1,2),1,2),widths=c(7,3.5))   ")
text=c(text,"plot(cumsum(-cf.i),xlim=xlim, ylim=ylim, main='Cash Flow',type='s',lwd=3,col='blue',ylab='$ millions')   ")
text=c(text,"if(!noval)  lines(v.i,type='b',col='red',pch=20,lwd=1)   ")
text=c(text,"abline(h=0)    ")
text=c(text,"plot.new()   ")
text=c(text,"legend('left',legend=c('Cum. net cash flow','NAV'),fill=c('blue','red'),cex=.9)   ")
text=c(text,"```   ")
text=c(text,"```{r echo=FALSE, fig.width=7, fig.height=7 }   ")
text=c(text,"layout(1)   ")
text=c(text,"benchind=grep('Russ',benchnames)   ")
text=c(text,"maintitle='Russell 2000'   ")
text=c(text,"if (pme.df$Portfolio[i]=='RE') {benchind=grep('ODCE',benchnames); maintitle='ODCE'}   ")
text=c(text,"if (pme.df$Portfolio[i] %in% c('OPP','PD')) {benchind=grep('Bond',benchnames); maintitle='Bond Index'}   ")
text=c(text,"benchc=bench.lst[[benchind]]   ")
text=c(text,"benchc=benchc[which(index(benchc)>=xlim[1])]   ")
text=c(text,"benchcgd=exp(cumsum(diff(log(benchc))))   ")
text=c(text,"par(mfrow=c(2,1))    ")
text=c(text,"plot(benchcgd,col='blue',main=maintitle,ylab='Growth of a $')   ")
text=c(text,"abline(h=1)   ")
text=c(text,"calls=-cf.i     ")
text=c(text,"calls[calls==0]=NA    ")
text=c(text,"plot(calls,xlim=xlim,type='p',pch=20,col='blue',main='Capital Calls/(Distributions)',ylab='$ millions')   ")
text=c(text,"abline(h=0)   ")
text=c(text,"```   ")
text=c(text,"   ")
text=c(text,"    ")
text=c(text,"   ")
if(hasperformancedata)  {
text=c(text,"```{r echo=FALSE, fig.width=20, fig.height=4 }   ")
text=c(text,"layout(matrix(c(1,2,3),1,3),widths=c(8,10,2))   ")
text=c(text,"color=gray(c(.7,.9))[1:ncol(xt)]    ")
text=c(text,"pme.ind=grep('PME',rownames(xt))   ")
text=c(text,"hpme.i=unlist(xt[pme.ind,])   ")
text=c(text,"hpme.i=matrix(hpme.i,ncol=length(benchnames),byrow=TRUE)   ")
text=c(text,"colnames(hpme.i)=benchnames   ")       
text=c(text,"bp=barplot(hpme.i,cex.axis=1.5,cex.main=1.8,cex.names=1.5
       ,beside=TRUE,main='Public Market Equivalents',col=color)   ")
text=c(text,"abline(h=1)   ")
text=c(text,"text(bp,0,as.vector(round(hpme.i,2)),pos=3,cex=1.4,col='blue')   ")
text=c(text,"irr.ind=grep('IRR',rownames(xt))   ")
text=c(text,"hirr.i=unlist(xt[irr.ind,])   ")
text=c(text,"hirr.i=matrix(hirr.i,ncol=1+length(benchnames),byrow=TRUE)   ")
text=c(text,"colnames(hirr.i)=c(benchnames,pme.df$name[i])   ")       
text=c(text,"bp=barplot(hirr.i,cex.axis=1.5,cex.main=1.8,cex.names=1.5
       ,beside=TRUE,main='Dollar Matched IRRs',col=color)   ")
text=c(text,"text(bp,0,as.vector(round(hirr.i,2)),pos=3,cex=1.4,col='blue')   ")
text=c(text,"plot.new()    ")
text=c(text,"legend('left',legend=colnames(xt),fill=color,cex=1.2)   ")
text=c(text,"```   ")
text=c(text,"   ")
text=c(text,"     ")
text=c(text,"   ")
text=c(text,"```{r echo=FALSE, fig.width=10, fig.height=6 }   ")
text=c(text,"layout(1)    ")
text=c(text,"fundsonly=which((pme.df$Portfolio==pme.df$Portfolio[i])&pme.df$isfund)   ")
text=c(text,"ytop=max(pme.df$Fund.IRR[i],50)   ")
text=c(text,"ymin=min(pme.df$Fund.IRR[i],-50)   ")
text=c(text,"xmin=min(.5,pme.df$Fund.TVPI[i])   ")
text=c(text,"plot.tvpi=pmax(xmin,pme.df$Fund.TVPI[fundsonly])   ")
text=c(text,"plot.irr=pmin(ytop,pmax(ymin,pme.df$Fund.IRR[fundsonly]))   ")
text=c(text,"plot(plot.tvpi,plot.irr,main=paste0('Comparison to ',pme.df$Portfolio[i],' Portfolio\n as of ',valdate),type='p',pch=20,col='blue',xlab='TVPI',ylab='IRR')   ")
text=c(text,"lines(pme.df$Fund.TVPI[i],pme.df$Fund.IRR[i],type='p',pch=19,col='red')   ")
text=c(text,"abline(h=0,v=1)   ")
text=c(text,"legend('topleft',legend=c(pme.df$name[i],paste(pme.df$Portfolio[i],'Portfolio')),fill=c('red','blue'))   ")
text=c(text,"```   ")
}
# text=c(text,"### Portfolio Investments")
# text=c(text,"```{r echo=FALSE, out.width=10, results='asis'}  ")
# text=c(text,"comps=read.csv(file='../priv market assets formatted.csv')   ")
# text=c(text,"comps.sub=subset(comps,comps$ShortName==pme.df$name[i])    ")
# text=c(text,"if (0==dim(comps.sub)[1]) {print('Portfolio information not available')} else {   ")
# text=c(text,"comps.sub$X=NULL    ")
# text=c(text,"comps.sub$ShortName=NULL    ")
# text=c(text,"print(xtable(comps.sub[order(-comps.sub$FMV.adj,na.last=TRUE),]),type='html') }   ")
# text=c(text,"```    ")
writeLines(text,filecon)
close(filecon)
knit2html(filename)
}       
         